CATEGORIES=['Tomato Bacterial spot',      
            'Tomato Early blight',
            'Tomato Late blight',
            'Tomato Leaf Mold',
            'Tomato Septoria leaf spot',
            'Tomato Spider mites Two-spotted spider mite',
            'Tomato Target Spot',
            'Tomato Tomato Yellow Leaf Curl Virus',
            'Tomato Tomato mosaic virus',
            'Tomato healthy']
